### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'hostname'

### ISSUE THREAD

**Issue by jwinns** [CalfCrusher/Poiana#2]
please help with this one:

* Starting tor network..
 * Creating hidden service in /home/kali/Poiana/hidden_service_data
Traceback (most recent call last):
  File "/home/kali/Poiana/poiana.py", line 141, in <module>
    main()
  File "/home/kali/Poiana/poiana.py", line 136, in main
    stem()
  File "/home/kali/Poiana/poiana.py", line 91, in stem
    if result.hostname:
AttributeError: 'NoneType' object has no attribute 'hostname'

**Comment by CalfCrusher** [comment]
Please check if hidden_service_data is already present when tool is running. If then remove that folder.

**Comment by jwinns** [comment]
thanks for the fast response!!!
But the hidden_service_data folder is not present.

**Comment by jwinns** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/23364193/132134450-8c92a843-6556-42f6-a60b-cae021d26abc.png)

**Comment by jwinns** [comment]
sorry, restart solved the problem. thx.
